# STUB — Replace with real Med-LLaMA call once model hosting is decided
# Real steps:
#   1. Format findings + patient metadata into prompt using REPORT_SYSTEM_PROMPT
#   2. Call Med-LLaMA via chosen provider API
#   3. Return generated clinical narrative string

from schemas import EEGFindings


def generate_report(findings: EEGFindings, patient_metadata: dict) -> str:
    print("[Report Generator] Generating report... (stub)")
    age = patient_metadata.get("age", "unknown")
    sex = patient_metadata.get("sex", "unknown")
    return (
        f"EEG Interpretation Report\n"
        f"Patient: {age}y {sex}\n\n"
        f"Findings demonstrate {findings.dominant_frequency_shift} with elevated "
        f"delta/theta power and reduced alpha activity. Inter-hemispheric frontal "
        f"coherence is reduced. AD risk score: {findings.ad_risk_score:.2f} (moderate). "
        f"Seizure risk: {findings.seizure_risk}.\n\n"
        f"Recommendation: Clinical correlation advised. Consider neuropsychological "
        f"evaluation given the pattern of findings. This report is generated by an "
        f"AI system and must be reviewed by a qualified clinician."
    )
